//
//  hokutoTenseiTableAbeshi.swift
//  SetteiSaCountApp
//
//  Created by 横田徹 on 2026/01/07.
//

import SwiftUI

struct hokutoTenseiTableAbeshi: View {
    @State var selectedItem: String = "設定変更以外"
    let itemList: [String] = ["設定変更以外","設定変更後",]
//    let maxWidth: CGFloat = 60
    let maxWidth: CGFloat = 50
    @State var numberDisplay: Bool = false
    var body: some View {
        VStack {
            Picker("", selection: self.$selectedItem) {
                ForEach(self.itemList, id: \.self) { item in
                    Text(item)
                }
            }
            .pickerStyle(.segmented)
            
            Toggle("設定1 選択率表示", isOn: self.$numberDisplay)
                .padding(.horizontal)
            
            if self.selectedItem == self.itemList[0] {
                HStack(spacing: 0) {
                    unitTableString(
                        columTitle: "",
                        stringList: [
                            "1〜64",
                            "65〜128",
                            "129〜192",
                            "193〜256",
                            "257〜320",
                            "321〜384",
                            "385〜448",
                            "449〜512",
                            "513〜576",
                            "577〜640",
                            "641〜704",
                            "705〜768",
                            "769〜832",
                            "833〜896",
                            "897〜960",
                            "961〜1024",
                            "1025〜1088",
                            "1089〜1152",
                            "1153〜1216",
                            "1217〜1280",
                            "1281〜1344",
                            "1345〜1408",
                            "1409〜1472",
                            "1473〜1536",
                        ],
                        maxWidth: 100,
                    )
                    if !self.numberDisplay {
                        unitTableString(
                            columTitle: "A",
                            stringList: [
                                "△",
                                "△",
                                "△",
                                "◎",
                                "△",
                                "△",
                                "△",
                                "△",
                                "◯",
                                "△",
                                "△",
                                "△",
                                "△",
                                "◯",
                                "△",
                                "△",
                                "△",
                                "△",
                                "△",
                                "◎",
                                "◯",
                                "◎",
                                "◎",
                                "天井",
                            ],
                            maxWidth: self.maxWidth,
                        )
                        unitTableString(
                            columTitle: "B",
                            stringList: [
                                "△",
                                "△",
                                "△",
                                "◎",
                                "△",
                                "◯",
                                "△",
                                "△",
                                "△",
                                "△",
                                "△",
                                "◯",
                                "△",
                                "天井",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                            ],
                            maxWidth: self.maxWidth,
                        )
                        unitTableString(
                            columTitle: "C",
                            stringList: [
                                "△",
                                "△",
                                "△",
                                "◎",
                                "△",
                                "△",
                                "△",
                                "△",
                                "天井",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                            ],
                            maxWidth: self.maxWidth,
                        )
                        unitTableString(
                            columTitle: "天国",
                            stringList: [
                                "◯",
                                "天井",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                            ],
                            maxWidth: self.maxWidth,
                        )
                    } else {
                        unitTablePercent(
                            columTitle: "A",
                            percentList: [
                                0.2,
                                1.37,
                                0.31,
                                21.94,
                                0.12,
                                0.73,
                                0.12,
                                0.12,
                                5.6,
                                0.11,
                                0.12,
                                1.4,
                                0.11,
                                5.71,
                                0.11,
                                0.71,
                                0.12,
                                0.73,
                                0.12,
                                10.99,
                                3.4,
                                15.11,
                                29.3,
                                1.45,
                            ],
                            numberofDicimal: 1,
                            maxWidth: self.maxWidth,
                        )
                        unitTablePercent(
                            columTitle: "B",
                            percentList: [
                                0.21,
                                1.49,
                                0.37,
                                26.59,
                                0.73,
                                4.41,
                                0.02,
                                0.02,
                                0.98,
                                0.99,
                                1.01,
                                12.23,
                                1,
                                49.93,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                            ],
                            numberofDicimal: 1,
                            maxWidth: self.maxWidth,
                        )
                        unitTablePercent(
                            columTitle: "C",
                            percentList: [
                                0.03,
                                0.20,
                                0.40,
                                28.81,
                                0.45,
                                2.7,
                                1.41,
                                1.38,
                                64.64,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                            ],
                            numberofDicimal: 1,
                            maxWidth: self.maxWidth,
                        )
                        unitTablePercent(
                            columTitle: "天国",
                            percentList: [
                                12.5,
                                87.5,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                            ],
                            numberofDicimal: 1,
                            maxWidth: self.maxWidth,
                        )
                    }
                }
            } else {
                HStack(spacing: 0) {
                    unitTableString(
                        columTitle: "",
                        stringList: [
                            "1〜64",
                            "65〜128",
                            "129〜192",
                            "193〜256",
                            "257〜320",
                            "321〜384",
                            "385〜448",
                            "449〜512",
                            "513〜576",
                            "577〜640",
                            "641〜704",
                            "705〜768",
                            "769〜832",
                            "833〜896",
                            "897〜960",
                            "961〜1024",
                            "1025〜1088",
                            "1089〜1152",
                            "1153〜1216",
                            "1217〜1280",
                            "1281〜1344",
                            "1345〜1408",
                            "1409〜1472",
                            "1473〜1536",
                        ],
                        maxWidth: 100,
                    )
                    if !self.numberDisplay {
                        unitTableString(
                            columTitle: "A",
                            stringList: [
                                "△",
                                "△",
                                "△",
                                "◎",
                                "△",
                                "△",
                                "△",
                                "△",
                                "◯",
                                "△",
                                "△",
                                "△",
                                "△",
                                "◯",
                                "△",
                                "◯",
                                "△",
                                "◯",
                                "△",
                                "天井",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                            ],
                            maxWidth: self.maxWidth,
                        )
                        unitTableString(
                            columTitle: "B",
                            stringList: [
                                "△",
                                "△",
                                "△",
                                "◎",
                                "△",
                                "◯",
                                "△",
                                "△",
                                "△",
                                "△",
                                "△",
                                "◎",
                                "△",
                                "天井",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                            ],
                            maxWidth: self.maxWidth,
                        )
                        unitTableString(
                            columTitle: "C",
                            stringList: [
                                "△",
                                "△",
                                "△",
                                "◎",
                                "△",
                                "△",
                                "△",
                                "△",
                                "天井",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                            ],
                            maxWidth: self.maxWidth,
                        )
                        unitTableString(
                            columTitle: "天国",
                            stringList: [
                                "◯",
                                "天井",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                                "grayOut",
                            ],
                            maxWidth: self.maxWidth,
                        )
                    } else {
                        unitTablePercent(
                            columTitle: "A",
                            percentList: [
                                0.26,
                                1.80,
                                0.36,
                                26.26,
                                0.15,
                                0.88,
                                0.15,
                                0.15,
                                6.71,
                                0.1,
                                0.1,
                                1.19,
                                0.1,
                                4.85,
                                0.89,
                                5.34,
                                0.89,
                                5.34,
                                0.89,
                                43.62,
                                -100,
                                -100,
                                -100,
                                -100,
                            ],
                            numberofDicimal: 1,
                            maxWidth: self.maxWidth,
                        )
                        unitTablePercent(
                            columTitle: "B",
                            percentList: [
                                0.29,
                                2.02,
                                0.45,
                                32.72,
                                0.9,
                                5.41,
                                0.03,
                                0.03,
                                1.21,
                                0.89,
                                0.89,
                                10.68,
                                0.89,
                                43.60,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                            ],
                            numberofDicimal: 1,
                            maxWidth: self.maxWidth,
                        )
                        unitTablePercent(
                            columTitle: "C",
                            percentList: [
                                0.03,
                                0.22,
                                0.40,
                                28.77,
                                0.45,
                                2.69,
                                1.40,
                                1.40,
                                64.63,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                            ],
                            numberofDicimal: 1,
                            maxWidth: self.maxWidth,
                        )
                        unitTablePercent(
                            columTitle: "天国",
                            percentList: [
                                12.5,
                                87.5,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                                -100,
                            ],
                            numberofDicimal: 1,
                            maxWidth: self.maxWidth,
                        )
                    }
                }
            }
        }
    }
}

#Preview {
    ScrollView {
        hokutoTenseiTableAbeshi(
            selectedItem: "設定変更後",
            numberDisplay: true,
        )
    }
    .padding(.horizontal)
}
